
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENT LPAREN NUMBER RPARENprogram : expressionexpression : NUMBER\n                   | IDENT\n                   | callcall : LPAREN expression_list RPARENexpression_list : expression\n                       | expression expression_list'
    
_lr_action_items = {'NUMBER':([0,3,4,5,6,8,9,],[3,-2,-3,-4,3,3,-5,]),'IDENT':([0,3,4,5,6,8,9,],[4,-2,-3,-4,4,4,-5,]),'LPAREN':([0,3,4,5,6,8,9,],[6,-2,-3,-4,6,6,-5,]),'$end':([1,2,3,4,5,9,],[0,-1,-2,-3,-4,-5,]),'RPAREN':([3,4,5,7,8,9,10,],[-2,-3,-4,9,-6,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expression':([0,6,8,],[2,8,8,]),'call':([0,6,8,],[5,5,5,]),'expression_list':([6,8,],[7,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> expression','program',1,'p_program','lisp-parser-relax.py',34),
  ('expression -> NUMBER','expression',1,'p_expression','lisp-parser-relax.py',38),
  ('expression -> IDENT','expression',1,'p_expression','lisp-parser-relax.py',39),
  ('expression -> call','expression',1,'p_expression','lisp-parser-relax.py',40),
  ('call -> LPAREN expression_list RPAREN','call',3,'p_call','lisp-parser-relax.py',44),
  ('expression_list -> expression','expression_list',1,'p_expression_list','lisp-parser-relax.py',48),
  ('expression_list -> expression expression_list','expression_list',2,'p_expression_list','lisp-parser-relax.py',49),
]
