MaxRep ← /↥⊕⧻ ⊛.
MaxRep "salama"

$ 32T3K 765
$ T55J5 684
$ KK677 28
$ KTJJT 220
$ QQQJA 483
regex "\\w+"
↯ [∞ 2]
# ≡⍜(⊡ 1)⋕
## ╭─                
## ╷ ⌜32T3K⌟ ⌜765⌟   
##   ⌜T55J5⌟ ⌜684⌟   
##   ⌜KK677⌟ ⌜28⌟    
##   ⌜KTJJT⌟ ⌜220⌟   
##   ⌜QQQJA⌟ ⌜483⌟   
##                 ╯ 

≡(°□⊢)
## ╭─          
## ╷ "32T3K"   
##   "T55J5"   
##   "KK677"   
##   "KTJJT"   
##   "QQQJA"   
##           ╯ 

.
≡MaxRep
## [2 3 2 2 3] 
⊕
## 3 
